//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_FlavourServices
    {
        public System.Guid ActivityFlavourServices_Id { get; set; }
        public System.Guid Activity_Flavour_Id { get; set; }
        public string FlavourServiceType { get; set; }
        public string Market { get; set; }
        public string RateMarket { get; set; }
        public string ServiceType { get; set; }
        public string ServiceTypeId { get; set; }
        public string ServiceCategory { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FromPax { get; set; }
        public string ToPax { get; set; }
        public string RateDivision { get; set; }
        public string RateActive { get; set; }
        public string RateCurrency { get; set; }
        public string AdultRate { get; set; }
        public string ChildRate { get; set; }
        public string InfantRate { get; set; }
        public string SeniorCitizenRate { get; set; }
        public string IncludeType { get; set; }
        public string CostBasis { get; set; }
        public string Session { get; set; }
        public string JourneyType { get; set; }
        public string Language { get; set; }
        public string GeneralNotes { get; set; }
        public string SpecificNotes { get; set; }
        public string PickupPoint { get; set; }
        public string DropoffPoint { get; set; }
        public string PickupTime { get; set; }
        public string DropoffTime { get; set; }
        public string Duration { get; set; }
        public string ServiceSupplier { get; set; }
        public string VenueType { get; set; }
        public string VenueName { get; set; }
        public string Drink { get; set; }
        public string Attributes { get; set; }
        public string Menu { get; set; }
        public string AvailableAtDisposal { get; set; }
        public string VehicleCategory { get; set; }
        public string VehicleClass { get; set; }
        public string VehicleACNONAC { get; set; }
        public string VehicleName { get; set; }
        public string Distance { get; set; }
    }
}
