//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierEntityValue
    {
        public System.Guid SupplierEntityValue_Id { get; set; }
        public Nullable<System.Guid> SupplierEntity_Id { get; set; }
        public Nullable<System.Guid> AttributeMap_Id { get; set; }
        public string SupplierValue { get; set; }
        public Nullable<System.Guid> AttributeValueMap_Id { get; set; }
        public string SupplierProperty { get; set; }
        public string SystemValue { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_User { get; set; }
    }
}
