//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TLGX_DEVEntities : DbContext
    {
        public TLGX_DEVEntities()
            : base("name=TLGX_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<Accommodation_ClassificationAttributes> Accommodation_ClassificationAttributes { get; set; }
        public virtual DbSet<Accommodation_Contact> Accommodation_Contact { get; set; }
        public virtual DbSet<Accommodation_Descriptions> Accommodation_Descriptions { get; set; }
        public virtual DbSet<Accommodation_Facility> Accommodation_Facility { get; set; }
        public virtual DbSet<Accommodation_HealthAndSafety> Accommodation_HealthAndSafety { get; set; }
        public virtual DbSet<Accommodation_HotelUpdates> Accommodation_HotelUpdates { get; set; }
        public virtual DbSet<Accommodation_Media> Accommodation_Media { get; set; }
        public virtual DbSet<Accommodation_NearbyPlaces> Accommodation_NearbyPlaces { get; set; }
        public virtual DbSet<Accommodation_PaxOccupancy> Accommodation_PaxOccupancy { get; set; }
        public virtual DbSet<Accommodation_RoomFacility> Accommodation_RoomFacility { get; set; }
        public virtual DbSet<Accommodation_RoomInfo> Accommodation_RoomInfo { get; set; }
        public virtual DbSet<Accommodation_RouteInfo> Accommodation_RouteInfo { get; set; }
        public virtual DbSet<Accommodation_RuleInfo> Accommodation_RuleInfo { get; set; }
        public virtual DbSet<Accommodation_Status> Accommodation_Status { get; set; }
        public virtual DbSet<DynamicAttribute> DynamicAttributes { get; set; }
        public virtual DbSet<Media_Attributes> Media_Attributes { get; set; }
        public virtual DbSet<m_CityArea> m_CityArea { get; set; }
        public virtual DbSet<m_CityAreaLocation> m_CityAreaLocation { get; set; }
        public virtual DbSet<m_CityMaster> m_CityMaster { get; set; }
        public virtual DbSet<m_CountryMaster> m_CountryMaster { get; set; }
        public virtual DbSet<m_States> m_States { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<m_CountryMapping> m_CountryMapping { get; set; }
        public virtual DbSet<m_CityMapping> m_CityMapping { get; set; }
        public virtual DbSet<Accommodation_ProductMapping> Accommodation_ProductMapping { get; set; }
        public virtual DbSet<Activity_Content> Activity_Content { get; set; }
        public virtual DbSet<Activity_SupplierProductMapping> Activity_SupplierProductMapping { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
    }
}
